scrape_configs:
  - job_name: 'ping'
    metrics_path: /probe
    params:
      module: [ping]
    static_configs:
      - targets:
          - 8.8.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'speedtest'
    metrics_path: /probe
    params:
      script: [speedtest]
    static_configs:
      - targets:
          - 'speedtest_exporter:9469'
    scrape_interval: 60m
    scrape_timeout: 90s
